services:

  db:
    image: postgres:18.1
    container_name: db-relatospapel
    restart: always
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_DB: 'dbrelatospapel'
      POSTGRES_USER: 'usrrelatospapel'
      POSTGRES_PASSWORD: 'Abc123relatos'
    ports:
      - '5433:5432'
  mysql:
    image: mysql:9.5
    container_name: mysql-relatospapel
    restart: always
    volumes:
      - ./sql/create_schema_mysql.sql:/docker-entrypoint-initdb.d/create_schema_mysql.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'Abc123relatosmysql'
      MYSQL_DATABASE: 'dbrelatospapelmysql'
      MYSQL_USER: 'usrrelatospapelmysql'
      MYSQL_PASSWORD: 'Abc123relatos'
      TZ: 'America/Guayaquil'
    ports:
      - '3307:3306'
